[2024-10-05T01:00:09.577+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-05T01:00:09.581+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_multiple_tasks_3.taskC scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-05T01:00:09.582+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_multiple_tasks_3.taskC scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-05T01:00:09.583+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-05T01:00:09.586+0100] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): taskC> on 2024-10-04 00:00:00+00:00
[2024-10-05T01:00:09.588+0100] {standard_task_runner.py:72} INFO - Started process 29310 to run task
[2024-10-05T01:00:09.590+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_multiple_tasks_3', 'taskC', 'scheduled__2024-10-04T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/execute_multiple_3.py', '--cfg-path', '/var/folders/nl/1x330z2x7yzb268yb0bbvjcr0000gn/T/tmpics_bu_w']
[2024-10-05T01:00:09.591+0100] {standard_task_runner.py:105} INFO - Job 61: Subtask taskC
[2024-10-05T01:00:09.603+0100] {task_command.py:467} INFO - Running <TaskInstance: executing_multiple_tasks_3.taskC scheduled__2024-10-04T00:00:00+00:00 [running]> on host mujtabas-macbook-pro.local
[2024-10-05T01:00:09.620+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ali' AIRFLOW_CTX_DAG_ID='executing_multiple_tasks_3' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T00:00:00+00:00'
[2024-10-05T01:00:09.620+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-05T01:00:09.625+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/nl/1x330z2x7yzb268yb0bbvjcr0000gn/T
[2024-10-05T01:00:09.626+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo TASK C has started!\nsleep 10\nexit 130\necho TASK C has ended!']
[2024-10-05T01:00:09.628+0100] {subprocess.py:86} INFO - Output:
[2024-10-05T01:00:09.630+0100] {subprocess.py:93} INFO - TASK C has started!
[2024-10-05T01:10:54.194+0100] {job.py:229} INFO - Heartbeat recovered after 644.63 seconds
[2024-10-05T01:10:54.198+0100] {local_task_job_runner.py:228} ERROR - Heartbeat time limit exceeded!
[2024-10-05T01:10:54.198+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-05T01:10:54.205+0100] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 29310. PIDs of all processes in the group: [29311, 29312, 29310]
[2024-10-05T01:10:54.205+0100] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 29310
[2024-10-05T01:10:54.206+0100] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-05T01:10:54.206+0100] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-10-05T01:10:54.207+0100] {process_utils.py:80} INFO - Process psutil.Process(pid=29312, status='terminated', started='01:00:09') (29312) terminated with exit code None
[2024-10-05T01:10:54.209+0100] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-10-05T01:10:54.212+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=executing_multiple_tasks_3, task_id=taskC, run_id=scheduled__2024-10-04T00:00:00+00:00, execution_date=20241004T000000, start_date=20241005T000009, end_date=20241005T001054
[2024-10-05T01:10:54.215+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-05T01:10:54.226+0100] {process_utils.py:80} INFO - Process psutil.Process(pid=29310, status='terminated', exitcode=2, started='01:00:09') (29310) terminated with exit code 2
[2024-10-05T01:10:54.226+0100] {process_utils.py:80} INFO - Process psutil.Process(pid=29311, status='terminated', started='01:00:09') (29311) terminated with exit code None
