[2024-10-08T02:26:52.686+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T02:26:52.691+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_multiple_tasks_3.taskC scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-08T02:26:52.694+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_multiple_tasks_3.taskC scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-08T02:26:52.694+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-08T02:26:52.698+0100] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): taskC> on 2024-10-07 00:00:00+00:00
[2024-10-08T02:26:52.700+0100] {standard_task_runner.py:72} INFO - Started process 4482 to run task
[2024-10-08T02:26:52.703+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_multiple_tasks_3', 'taskC', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/execute_multiple_3.py', '--cfg-path', '/var/folders/nl/1x330z2x7yzb268yb0bbvjcr0000gn/T/tmpkq83vz89']
[2024-10-08T02:26:52.704+0100] {standard_task_runner.py:105} INFO - Job 97: Subtask taskC
[2024-10-08T02:26:52.717+0100] {task_command.py:467} INFO - Running <TaskInstance: executing_multiple_tasks_3.taskC scheduled__2024-10-07T00:00:00+00:00 [running]> on host mujtabas-macbook-pro.local
[2024-10-08T02:26:52.736+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ali' AIRFLOW_CTX_DAG_ID='executing_multiple_tasks_3' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2024-10-08T02:26:52.736+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T02:26:52.741+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/nl/1x330z2x7yzb268yb0bbvjcr0000gn/T
[2024-10-08T02:26:52.742+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo TASK C has started!\nsleep 10\nexit 130\necho TASK C has ended!']
[2024-10-08T02:26:52.744+0100] {subprocess.py:86} INFO - Output:
[2024-10-08T02:26:52.745+0100] {subprocess.py:93} INFO - TASK C has started!
[2024-10-08T02:43:15.419+0100] {job.py:229} INFO - Heartbeat recovered after 982.77 seconds
[2024-10-08T03:00:31.106+0100] {subprocess.py:97} INFO - Command exited with return code 130
[2024-10-08T03:00:31.115+0100] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2024-10-08T03:00:31.120+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=executing_multiple_tasks_3, task_id=taskC, run_id=scheduled__2024-10-07T00:00:00+00:00, execution_date=20241007T000000, start_date=20241008T012652, end_date=20241008T020031
[2024-10-08T03:00:31.129+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T03:00:31.131+0100] {job.py:229} INFO - Heartbeat recovered after 1035.72 seconds
[2024-10-08T03:00:31.129+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 97 for task taskC (Bash command failed. The command returned a non-zero exit code 130.; 4482)
Traceback (most recent call last):
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2024-10-08T03:00:31.134+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-08T03:00:31.143+0100] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T03:00:31.145+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
