[2024-10-17T21:15:36.258+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T21:15:36.263+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_branching.not_eligible_to_drive scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T21:15:36.265+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_branching.not_eligible_to_drive scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T21:15:36.266+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-17T21:15:36.269+0100] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): not_eligible_to_drive> on 2024-10-16 00:00:00+00:00
[2024-10-17T21:15:36.271+0100] {standard_task_runner.py:72} INFO - Started process 2769 to run task
[2024-10-17T21:15:36.274+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_branching', 'not_eligible_to_drive', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '240', '--raw', '--subdir', 'DAGS_FOLDER/branching.py', '--cfg-path', '/var/folders/nl/1x330z2x7yzb268yb0bbvjcr0000gn/T/tmpwadpo32k']
[2024-10-17T21:15:36.275+0100] {standard_task_runner.py:105} INFO - Job 240: Subtask not_eligible_to_drive
[2024-10-17T21:15:36.287+0100] {task_command.py:467} INFO - Running <TaskInstance: executing_branching.not_eligible_to_drive scheduled__2024-10-16T00:00:00+00:00 [running]> on host mujtabas-macbook-pro.local
[2024-10-17T21:15:36.304+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ali' AIRFLOW_CTX_DAG_ID='executing_branching' AIRFLOW_CTX_TASK_ID='not_eligible_to_drive' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T21:15:36.305+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T21:15:36.310+0100] {logging_mixin.py:190} INFO - I'm afraid you are out of luck, you need a license to drive
[2024-10-17T21:15:36.310+0100] {python.py:240} INFO - Done. Returned value was: None
[2024-10-17T21:15:36.312+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T21:15:36.312+0100] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=executing_branching, task_id=not_eligible_to_drive, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T201536, end_date=20241017T201536
[2024-10-17T21:15:36.335+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-17T21:15:36.340+0100] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T21:15:36.341+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
